name: OWASP ZAP Full Scan

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target URL to be analyzed'
        required: true
        default: 'https://demo-pedro-prod.azurewebsites.net/'
#         default: 'https://www.zaproxy.org/'

jobs:
  zap-scan:
    runs-on: ubuntu-latest
    name: Scan the web application

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          target: ${{ github.event.inputs.target }}
          cmd_options: '-z "-config view.locale=pt_BR"'
