 name: OWASP ZAP Full Scan
 
 on:
  workflow_dispatch:
  
jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
  
    steps:
     - name: Checkout
       uses: actions/checkout@v2
